package annvisitor.util;

public enum ResultKind {
    ARGUMENT_MISMATCH,
    TYPE_MISMATCH_OPERAND,
    WRONG_APPLY_OPERATOR,
    INCORRECT_RETURN_TYPE,
    ANNOTATION_ON_VOID,
    NON_ANNOTATED_PARAM_WARNING,
    UNSAFE_TYPE_CAST,
    OK
}