package scanner.util;

public enum ErrorAndWarningKind {
    ARGUMENT_MISMATCH,
    TYPE_MISMATCH_OPERAND,
    WRONG_APPLY_OPERATOR,
    UNKNOWN_TYPE_ASSIGNMENT,
    UNKNOWN_TYPE_PARAM,
    MISSING_ANNOTATION_ON_FIELD,
    INCORRECT_RETURN_TYPE,
    ANNOTATION_ON_VOID,
    UNSAFE_TYPE_CAST
}